var searchData=
[
  ['random_2604',['Random',['../classtesting_1_1internal_1_1Random.html',1,'testing::internal']]],
  ['randomaccessrepeatedfieldaccessor_2605',['RandomAccessRepeatedFieldAccessor',['../classgoogle_1_1protobuf_1_1internal_1_1RandomAccessRepeatedFieldAccessor.html',1,'google::protobuf::internal']]],
  ['rangegenerator_2606',['RangeGenerator',['../classtesting_1_1internal_1_1RangeGenerator.html',1,'testing::internal']]],
  ['rangenode_2607',['RangeNode',['../classpump_1_1RangeNode.html',1,'pump']]],
  ['rawcodenode_2608',['RawCodeNode',['../classpump_1_1RawCodeNode.html',1,'pump']]],
  ['re_2609',['RE',['../classtesting_1_1internal_1_1RE.html',1,'testing::internal']]],
  ['reactor_2610',['Reactor',['../classtinyrpc_1_1Reactor.html',1,'tinyrpc']]],
  ['reader_2611',['Reader',['../classJson_1_1Reader.html',1,'Json']]],
  ['readscopedlockimpl_2612',['ReadScopedLockImpl',['../structtinyrpc_1_1ReadScopedLockImpl.html',1,'tinyrpc']]],
  ['rebind_2613',['rebind',['../structgoogle_1_1protobuf_1_1internal_1_1MapAllocator_1_1rebind.html',1,'google::protobuf::internal::MapAllocator']]],
  ['reflection_2614',['Reflection',['../classgoogle_1_1protobuf_1_1Reflection.html',1,'google::protobuf']]],
  ['reflectionclassgenerator_2615',['ReflectionClassGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1csharp_1_1ReflectionClassGenerator.html',1,'google::protobuf::compiler::csharp']]],
  ['reflectionops_2616',['ReflectionOps',['../classgoogle_1_1protobuf_1_1internal_1_1ReflectionOps.html',1,'google::protobuf::internal']]],
  ['reflectionschema_2617',['ReflectionSchema',['../structgoogle_1_1protobuf_1_1internal_1_1ReflectionSchema.html',1,'google::protobuf::internal']]],
  ['reflectiontester_2618',['ReflectionTester',['../classgoogle_1_1protobuf_1_1TestUtil_1_1ReflectionTester.html',1,'google::protobuf::TestUtil']]],
  ['reftypetraits_2619',['RefTypeTraits',['../structgoogle_1_1protobuf_1_1internal_1_1RefTypeTraits.html',1,'google::protobuf::internal']]],
  ['reftypetraits_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20is_5fproto_5fenum_3c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_2620',['RefTypeTraits&lt; T, typename std::enable_if&lt; is_proto_enum&lt; T &gt;::value &gt;::type &gt;',['../structgoogle_1_1protobuf_1_1internal_1_1RefTypeTraits_3_01T_00_01typename_01std_1_1enable__if_3_42df78e4729c6a4d9c3281fd7cdc6539.html',1,'google::protobuf::internal']]],
  ['reftypetraits_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20primitivetraits_3c_20t_20_3e_3a_3ais_5fprimitive_20_3e_3a_3atype_20_3e_2621',['RefTypeTraits&lt; T, typename std::enable_if&lt; PrimitiveTraits&lt; T &gt;::is_primitive &gt;::type &gt;',['../structgoogle_1_1protobuf_1_1internal_1_1RefTypeTraits_3_01T_00_01typename_01std_1_1enable__if_3_90227f0229628c286c3b17e433456602.html',1,'google::protobuf::internal']]],
  ['reftypetraits_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fbase_5fof_3c_20message_2c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_2622',['RefTypeTraits&lt; T, typename std::enable_if&lt; std::is_base_of&lt; Message, T &gt;::value &gt;::type &gt;',['../structgoogle_1_1protobuf_1_1internal_1_1RefTypeTraits_3_01T_00_01typename_01std_1_1enable__if_3_82f25cb7986b5af3792a532b263e1d42.html',1,'google::protobuf::internal']]],
  ['reftypetraits_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fsame_3c_20std_3a_3astring_2c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_2623',['RefTypeTraits&lt; T, typename std::enable_if&lt; std::is_same&lt; std::string, T &gt;::value &gt;::type &gt;',['../structgoogle_1_1protobuf_1_1internal_1_1RefTypeTraits_3_01T_00_01typename_01std_1_1enable__if_3_90eb1404b3a79aae0d16c7024a783256.html',1,'google::protobuf::internal']]],
  ['relationtosourcecopy_2624',['RelationToSourceCopy',['../structtesting_1_1internal_1_1RelationToSourceCopy.html',1,'testing::internal']]],
  ['relationtosourcereference_2625',['RelationToSourceReference',['../structtesting_1_1internal_1_1RelationToSourceReference.html',1,'testing::internal']]],
  ['remapentry_2626',['RemapEntry',['../structgoogle_1_1protobuf_1_1internal_1_1RemapEntry.html',1,'google::protobuf::internal']]],
  ['remove_5freference_2627',['remove_reference',['../structtesting_1_1internal_1_1remove__reference.html',1,'testing::internal']]],
  ['remove_5freference_3c_20t_20_26_20_3e_2628',['remove_reference&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1remove__reference_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['removeconst_2629',['RemoveConst',['../structgoogle_1_1protobuf_1_1internal_1_1RemoveConst.html',1,'google::protobuf::internal::RemoveConst&lt; T &gt;'],['../structtesting_1_1internal_1_1RemoveConst.html',1,'testing::internal::RemoveConst&lt; T &gt;']]],
  ['removeconst_3c_20const_20t_20_3e_2630',['RemoveConst&lt; const T &gt;',['../structgoogle_1_1protobuf_1_1internal_1_1RemoveConst_3_01const_01T_01_4.html',1,'google::protobuf::internal::RemoveConst&lt; const T &gt;'],['../structtesting_1_1internal_1_1RemoveConst_3_01const_01T_01_4.html',1,'testing::internal::RemoveConst&lt; const T &gt;']]],
  ['removeconst_3c_20const_20t_5bn_5d_3e_2631',['RemoveConst&lt; const T[N]&gt;',['../structtesting_1_1internal_1_1RemoveConst_3_01const_01T_0fN_0e_4.html',1,'testing::internal']]],
  ['removeconstfromkey_2632',['RemoveConstFromKey',['../structtesting_1_1internal_1_1RemoveConstFromKey.html',1,'testing::internal']]],
  ['removeconstfromkey_3c_20std_3a_3apair_3c_20const_20k_2c_20v_20_3e_20_3e_2633',['RemoveConstFromKey&lt; std::pair&lt; const K, V &gt; &gt;',['../structtesting_1_1internal_1_1RemoveConstFromKey_3_01std_1_1pair_3_01const_01K_00_01V_01_4_01_4.html',1,'testing::internal']]],
  ['removereference_2634',['RemoveReference',['../structtesting_1_1internal_1_1RemoveReference.html',1,'testing::internal']]],
  ['removereference_3c_20t_20_26_20_3e_2635',['RemoveReference&lt; T &amp; &gt;',['../structtesting_1_1internal_1_1RemoveReference_3_01T_01_6_01_4.html',1,'testing::internal']]],
  ['renderoptions_2636',['RenderOptions',['../structgoogle_1_1protobuf_1_1util_1_1converter_1_1ProtoStreamObjectSource_1_1RenderOptions.html',1,'google::protobuf::util::converter::ProtoStreamObjectSource']]],
  ['repeatedenumfieldgenerator_2637',['RepeatedEnumFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1cpp_1_1RepeatedEnumFieldGenerator.html',1,'google::protobuf::compiler::cpp::RepeatedEnumFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1csharp_1_1RepeatedEnumFieldGenerator.html',1,'google::protobuf::compiler::csharp::RepeatedEnumFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1objectivec_1_1RepeatedEnumFieldGenerator.html',1,'google::protobuf::compiler::objectivec::RepeatedEnumFieldGenerator']]],
  ['repeatedenumtypetraits_2638',['RepeatedEnumTypeTraits',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedEnumTypeTraits.html',1,'google::protobuf::internal']]],
  ['repeatedfield_2639',['RepeatedField',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20bool_20_3e_2640',['RepeatedField&lt; bool &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20double_20_3e_2641',['RepeatedField&lt; double &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20float_20_3e_2642',['RepeatedField&lt; float &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20int_20_3e_2643',['RepeatedField&lt; int &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20int32_5ft_20_3e_2644',['RepeatedField&lt; int32_t &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20int64_5ft_20_3e_2645',['RepeatedField&lt; int64_t &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20t_20_3e_2646',['RepeatedField&lt; T &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20uint32_5ft_20_3e_2647',['RepeatedField&lt; uint32_t &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfield_3c_20uint64_5ft_20_3e_2648',['RepeatedField&lt; uint64_t &gt;',['../classgoogle_1_1protobuf_1_1RepeatedField.html',1,'google::protobuf']]],
  ['repeatedfieldaccessor_2649',['RepeatedFieldAccessor',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedFieldAccessor.html',1,'google::protobuf::internal']]],
  ['repeatedfieldbackinsertiterator_2650',['RepeatedFieldBackInsertIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedFieldBackInsertIterator.html',1,'google::protobuf::internal']]],
  ['repeatedfieldgenerator_2651',['RepeatedFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1objectivec_1_1RepeatedFieldGenerator.html',1,'google::protobuf::compiler::objectivec']]],
  ['repeatedfieldprimitiveaccessor_2652',['RepeatedFieldPrimitiveAccessor',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedFieldPrimitiveAccessor.html',1,'google::protobuf::internal']]],
  ['repeatedfieldref_2653',['RepeatedFieldRef',['../classgoogle_1_1protobuf_1_1RepeatedFieldRef.html',1,'google::protobuf']]],
  ['repeatedfieldref_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_20std_3a_3ais_5fbase_5fof_3c_20message_2c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_2654',['RepeatedFieldRef&lt; T, typename std::enable_if&lt; std::is_base_of&lt; Message, T &gt;::value &gt;::type &gt;',['../classgoogle_1_1protobuf_1_1RepeatedFieldRef_3_01T_00_01typename_01std_1_1enable__if_3_01std_1_1ib218d520805b655e7c99a48c5bbfabf9.html',1,'google::protobuf']]],
  ['repeatedfieldref_3c_20t_2c_20typename_20std_3a_3aenable_5fif_3c_21std_3a_3ais_5fbase_5fof_3c_20message_2c_20t_20_3e_3a_3avalue_20_3e_3a_3atype_20_3e_2655',['RepeatedFieldRef&lt; T, typename std::enable_if&lt;!std::is_base_of&lt; Message, T &gt;::value &gt;::type &gt;',['../classgoogle_1_1protobuf_1_1RepeatedFieldRef_3_01T_00_01typename_01std_1_1enable__if_3_9std_1_1is63c3c9eaea1cf7d7d78b6d1712dc85a3.html',1,'google::protobuf']]],
  ['repeatedfieldrefiterator_2656',['RepeatedFieldRefIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedFieldRefIterator.html',1,'google::protobuf::internal']]],
  ['repeatedfieldwrapper_2657',['RepeatedFieldWrapper',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedFieldWrapper.html',1,'google::protobuf::internal']]],
  ['repeatedimmutableenumfieldgenerator_2658',['RepeatedImmutableEnumFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableEnumFieldGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutableenumfieldlitegenerator_2659',['RepeatedImmutableEnumFieldLiteGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableEnumFieldLiteGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutablemessagefieldgenerator_2660',['RepeatedImmutableMessageFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableMessageFieldGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutablemessagefieldlitegenerator_2661',['RepeatedImmutableMessageFieldLiteGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableMessageFieldLiteGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutableprimitivefieldgenerator_2662',['RepeatedImmutablePrimitiveFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutablePrimitiveFieldGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutableprimitivefieldlitegenerator_2663',['RepeatedImmutablePrimitiveFieldLiteGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutablePrimitiveFieldLiteGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutablestringfieldgenerator_2664',['RepeatedImmutableStringFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableStringFieldGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatedimmutablestringfieldlitegenerator_2665',['RepeatedImmutableStringFieldLiteGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1java_1_1RepeatedImmutableStringFieldLiteGenerator.html',1,'google::protobuf::compiler::java']]],
  ['repeatediterator_2666',['RepeatedIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedIterator.html',1,'google::protobuf::internal']]],
  ['repeatedmessagefieldgenerator_2667',['RepeatedMessageFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1cpp_1_1RepeatedMessageFieldGenerator.html',1,'google::protobuf::compiler::cpp::RepeatedMessageFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1csharp_1_1RepeatedMessageFieldGenerator.html',1,'google::protobuf::compiler::csharp::RepeatedMessageFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1objectivec_1_1RepeatedMessageFieldGenerator.html',1,'google::protobuf::compiler::objectivec::RepeatedMessageFieldGenerator']]],
  ['repeatedmessagetypetraits_2668',['RepeatedMessageTypeTraits',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedMessageTypeTraits.html',1,'google::protobuf::internal']]],
  ['repeatedprimitivedefaults_2669',['RepeatedPrimitiveDefaults',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPrimitiveDefaults.html',1,'google::protobuf::internal']]],
  ['repeatedprimitivefieldgenerator_2670',['RepeatedPrimitiveFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1cpp_1_1RepeatedPrimitiveFieldGenerator.html',1,'google::protobuf::compiler::cpp::RepeatedPrimitiveFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1csharp_1_1RepeatedPrimitiveFieldGenerator.html',1,'google::protobuf::compiler::csharp::RepeatedPrimitiveFieldGenerator'],['../classgoogle_1_1protobuf_1_1compiler_1_1objectivec_1_1RepeatedPrimitiveFieldGenerator.html',1,'google::protobuf::compiler::objectivec::RepeatedPrimitiveFieldGenerator']]],
  ['repeatedprimitivetypetraits_2671',['RepeatedPrimitiveTypeTraits',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPrimitiveTypeTraits.html',1,'google::protobuf::internal']]],
  ['repeatedptrfield_2672',['RepeatedPtrField',['../classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['repeatedptrfield_3c_20google_3a_3aprotobuf_3a_3amessage_20_3e_2673',['RepeatedPtrField&lt; google::protobuf::Message &gt;',['../classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['repeatedptrfield_3c_20google_3a_3aprotobuf_3a_3amessagelite_20_3e_2674',['RepeatedPtrField&lt; google::protobuf::MessageLite &gt;',['../classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['repeatedptrfield_3c_20std_3a_3astring_20_3e_2675',['RepeatedPtrField&lt; std::string &gt;',['../classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['repeatedptrfield_3c_20t_20_3e_2676',['RepeatedPtrField&lt; T &gt;',['../classgoogle_1_1protobuf_1_1RepeatedPtrField.html',1,'google::protobuf']]],
  ['repeatedptrfieldbackinsertiterator_2677',['RepeatedPtrFieldBackInsertIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldBackInsertIterator.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldbase_2678',['RepeatedPtrFieldBase',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldBase.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldmessageaccessor_2679',['RepeatedPtrFieldMessageAccessor',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldMessageAccessor.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldstringaccessor_2680',['RepeatedPtrFieldStringAccessor',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldStringAccessor.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldwrapper_2681',['RepeatedPtrFieldWrapper',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldWrapper.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldwrapper_3c_20message_20_3e_2682',['RepeatedPtrFieldWrapper&lt; Message &gt;',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldWrapper.html',1,'google::protobuf::internal']]],
  ['repeatedptrfieldwrapper_3c_20std_3a_3astring_20_3e_2683',['RepeatedPtrFieldWrapper&lt; std::string &gt;',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrFieldWrapper.html',1,'google::protobuf::internal']]],
  ['repeatedptriterator_2684',['RepeatedPtrIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrIterator.html',1,'google::protobuf::internal']]],
  ['repeatedptroverptrsiterator_2685',['RepeatedPtrOverPtrsIterator',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedPtrOverPtrsIterator.html',1,'google::protobuf::internal']]],
  ['repeatedstringfieldgenerator_2686',['RepeatedStringFieldGenerator',['../classgoogle_1_1protobuf_1_1compiler_1_1cpp_1_1RepeatedStringFieldGenerator.html',1,'google::protobuf::compiler::cpp']]],
  ['repeatedstringtypetraits_2687',['RepeatedStringTypeTraits',['../classgoogle_1_1protobuf_1_1internal_1_1RepeatedStringTypeTraits.html',1,'google::protobuf::internal']]],
  ['reporter_2688',['Reporter',['../classgoogle_1_1protobuf_1_1util_1_1MessageDifferencer_1_1Reporter.html',1,'google::protobuf::util::MessageDifferencer']]],
  ['reserveddescriptortest_2689',['ReservedDescriptorTest',['../classgoogle_1_1protobuf_1_1descriptor__unittest_1_1ReservedDescriptorTest.html',1,'google::protobuf::descriptor_unittest']]],
  ['reservedenumdescriptortest_2690',['ReservedEnumDescriptorTest',['../classgoogle_1_1protobuf_1_1descriptor__unittest_1_1ReservedEnumDescriptorTest.html',1,'google::protobuf::descriptor_unittest']]],
  ['reservedrange_2691',['ReservedRange',['../structgoogle_1_1protobuf_1_1Descriptor_1_1ReservedRange.html',1,'google::protobuf::Descriptor::ReservedRange'],['../structgoogle_1_1protobuf_1_1EnumDescriptor_1_1ReservedRange.html',1,'google::protobuf::EnumDescriptor::ReservedRange']]],
  ['resultcallback_2692',['ResultCallback',['../classgoogle_1_1protobuf_1_1ResultCallback.html',1,'google::protobuf']]],
  ['resultcallback1_2693',['ResultCallback1',['../classgoogle_1_1protobuf_1_1ResultCallback1.html',1,'google::protobuf']]],
  ['resultcallback1_3c_20r_2c_20arg1_20_3e_2694',['ResultCallback1&lt; R, Arg1 &gt;',['../classgoogle_1_1protobuf_1_1ResultCallback1.html',1,'google::protobuf']]],
  ['resultcallback2_2695',['ResultCallback2',['../classgoogle_1_1protobuf_1_1ResultCallback2.html',1,'google::protobuf']]],
  ['return_2696',['Return',['../classcpp_1_1ast_1_1Return.html',1,'cpp::ast']]],
  ['returnaction_2697',['ReturnAction',['../classtesting_1_1internal_1_1ReturnAction.html',1,'testing::internal']]],
  ['returnnullaction_2698',['ReturnNullAction',['../classtesting_1_1internal_1_1ReturnNullAction.html',1,'testing::internal']]],
  ['returnrefaction_2699',['ReturnRefAction',['../classtesting_1_1internal_1_1ReturnRefAction.html',1,'testing::internal']]],
  ['returnrefofcopyaction_2700',['ReturnRefOfCopyAction',['../classtesting_1_1internal_1_1ReturnRefOfCopyAction.html',1,'testing::internal']]],
  ['returnvoidaction_2701',['ReturnVoidAction',['../classtesting_1_1internal_1_1ReturnVoidAction.html',1,'testing::internal']]],
  ['rpcchannel_2702',['RpcChannel',['../classgoogle_1_1protobuf_1_1RpcChannel.html',1,'google::protobuf']]],
  ['rpccontroller_2703',['RpcController',['../classgoogle_1_1protobuf_1_1RpcController.html',1,'google::protobuf']]],
  ['runtime_2704',['RunTime',['../classtinyrpc_1_1RunTime.html',1,'tinyrpc']]],
  ['runtimeerror_2705',['RuntimeError',['../classJson_1_1RuntimeError.html',1,'Json']]],
  ['rwmutex_2706',['RWMutex',['../classtinyrpc_1_1RWMutex.html',1,'tinyrpc']]]
];
